.TH IDEN 1 nade-utils\-VERSION
.SH NAME
iden \- check if two files are identical
.SH SYNOPSIS
.B iden [ file1 file2 ]
.SH DESCRIPTION
iden is a tiny tool that checks if two files are identical. iden will
return 0 if the files are identical, 1 otherwise.
.br

.SH BUGS
Please report any bugs or share any suggestions by hitting me a /msg on irc:
dwts@freenode, by sending a mail  or join #ninja-turtles @freenode.

.SH REPO
The repository of nade-utils can be found here:
https://github.com/s-p-k/nade-utils

.SH COPYRIGHT
Copyright (c) 2014-2015, Pavlos Moysidis (mr.dwts@gmail.com)
