.TH IDEN 1 "February 2014"
.SH NAME
iden \- check if two files are identical
.SH SYNOPSIS
.B iden [ file1 file2 ]
.SH DESCRIPTION
iden is a tiny tool that checks if two files are identical. iden will
return 0 if the files are identical, 1 otherwise.
.br

.SH BUGS
Please report any bugs or share any suggestions by hitting me a /msg on irc:
dwts@freenode or join #ninja-turtles @freenode.

.SH COPYRIGHT
Copyright (c) 2014, spk (mr.dwts@gmail.com)
